FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Services/Basket/FreeCourseServices.Basket/*.csproj Services/Basket/FreeCourseServices.Basket/
RUN dotnet restore Services/Basket/FreeCourseServices.Basket/*.csproj
COPY . .
RUN dotnet publish Services/Basket/FreeCourseServices.Basket/*.csproj -c Relase -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","FreeCourseServices.Basket.dll" ]