FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Services/Catalog/FreeCourseServicesCatalog/*.csproj Services/Catalog/FreeCourseServicesCatalog/
RUN dotnet restore Services/Catalog/FreeCourseServicesCatalog/*.csproj
COPY . .
RUN dotnet publish Services/Catalog/FreeCourseServicesCatalog/*.csproj -c Relase -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","FreeCourseServices.Catalog.dll" ]