FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Services/Discount/FreeCourseServices.Discount/*.csproj Services/Discount/FreeCourseServices.Discount/
RUN dotnet restore Services/Discount/FreeCourseServices.Discount/*.csproj
COPY . .
RUN dotnet publish Services/Discount/FreeCourseServices.Discount/*.csproj -c Relase -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","FreeCourseServices.Discount.dll" ]