FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Frontends/FreeCourse.WebUI/*.csproj Frontends/FreeCourse.WebUI/
RUN dotnet restore Frontends/FreeCourse.WebUI/*.csproj
COPY . .
RUN dotnet publish Frontends/FreeCourse.WebUI/*.csproj -c Relase -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","FreeCourse.WebUI.dll" ]