FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/

COPY Services/Order/FreeCourseServices.OrderApplication/*.csproj Services/Order/FreeCourseServices.OrderApplication/
COPY Services/Order/FreeCourseServices.OrderDomain/*.csproj Services/Order/FreeCourseServices.OrderDomain/
COPY Services/Order/FreeCourseServices.OrderDomainCore/*.csproj Services/Order/FreeCourseServices.OrderDomainCore/
COPY Services/Order/FreeCourseServices.OrderInfrastructure/*.csproj Services/Order/FreeCourseServices.OrderInfrastructure/

COPY Services/Order/FreeCourseServices.OrderAPI/*.csproj Services/Order/FreeCourseServices.OrderAPI/
RUN dotnet restore Services/Order/FreeCourseServices.OrderAPI/*.csproj
COPY . .
RUN dotnet publish Services/Order/FreeCourseServices.OrderAPI/*.csproj -c Relase -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","FreeCourseServices.OrderAPI.dll" ]