FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/FreeCourse.Shared/*.csproj Shared/FreeCourse.Shared/
COPY Services/PhotoStock/FreeCourseServices.PhotoStock/*.csproj Services/PhotoStock/FreeCourseServices.PhotoStock/
RUN dotnet restore Services/PhotoStock/FreeCourseServices.PhotoStock/*.csproj
COPY . .
RUN dotnet publish Services/PhotoStock/FreeCourseServices.PhotoStock/*.csproj -c Relase -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","FreeCourseServices.PhotoStock.dll" ]